// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ARTIFICIAL_HORIZON_PAGE_H
#define UI_ARTIFICIAL_HORIZON_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Artificial_Horizon_Page
extern void ui_Artificial_Horizon_Page_screen_init(void);
extern void ui_Artificial_Horizon_Page_screen_destroy(void);
extern lv_obj_t * ui_Artificial_Horizon_Page;
extern lv_obj_t * ui_ArtificialHorizonPageLabel;
extern void ui_event_Page2HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page2HomeBTN;
extern lv_obj_t * ui_HomeBTN1;
extern void ui_event_Page2PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page2PrevBTN;
extern lv_obj_t * ui_Page2PrevBTN1;
extern void ui_event_Page2NextBTN2(lv_event_t * e);
extern lv_obj_t * ui_Page2NextBTN2;
extern lv_obj_t * ui_Page2NextBTN;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ArtificialHorizon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

