// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"              // Main UI include from SquareLine Studio
#include "ui_modern_theme.h" // DEADEYE theme support

#include <cstdio> // For snprintf
#include <cmath>  // For fabsf

// --- Color threshold constants ---
#define BUBBLE_LEVEL_THRESHOLD_GREEN 3.0f
#define BUBBLE_LEVEL_THRESHOLD_YELLOW 8.0f

// --- Definitions for the Bubble Level ---
#define LEVEL_CANVAS_WIDTH 200
#define LEVEL_CANVAS_HEIGHT 40
#define TUBE_WIDTH (LEVEL_CANVAS_WIDTH - 10)
#define TUBE_HEIGHT (LEVEL_CANVAS_HEIGHT - 10)
#define TUBE_BORDER_RADIUS 8
#define BUBBLE_HEIGHT (TUBE_HEIGHT - 2)
#define BUBBLE_WIDTH (BUBBLE_HEIGHT + 12)
#define MAX_ROLL_ANGLE 30.0f

// --- Colors for the Bubble Level - DEADEYE Theme ---
static lv_color_t color_page_bg_bubble;
static lv_color_t color_tube_bg_bubble;
static lv_color_t color_bubble_green;
static lv_color_t color_bubble_yellow;
static lv_color_t color_bubble_red;
static lv_color_t color_text_roll_label;
static lv_color_t color_tube_marking_bubble;

// --- LVGL Objects for the Bubble Level (static to this file/module) ---
static lv_obj_t *ui_BubbleLevelCanvas = nullptr;
static lv_obj_t *ui_RollAngleLabel = nullptr;
static lv_timer_t *ui_level_update_timer = nullptr;

// --- Forward declarations for bubble level helper functions ---
static void draw_bubble_level_on_canvas(float roll_angle_deg);
static void level_update_timer_cb(lv_timer_t *timer);

// --- SquareLine Studio Global Variables (defined in this file by SLS) ---
lv_obj_t *ui_Bubble_Level_Page = nullptr;
lv_obj_t *ui_BubbleLevelPageLabel = nullptr;
lv_obj_t *ui_Page1HomeBTN = nullptr;
lv_obj_t *ui_Pg1HomeBTN = nullptr;
lv_obj_t *ui_Page1NextBTN1 = nullptr;
lv_obj_t *ui_Page1NextBTN = nullptr;
lv_obj_t *ui_Page1PrevBTN = nullptr;
lv_obj_t *ui_Page1PrevBTN1 = nullptr;

// --- Event functions (from your provided .c file) ---
void ui_event_Page1HomeBTN(lv_event_t *e)
{
    // ...existing code...
}
// ...existing code for the rest of the file...
