// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui_helpers.h"

void _ui_bar_set_property(lv_obj_t *target, int id, int val)
{
    if (id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM)
        lv_bar_set_value(target, val, LV_ANIM_ON);
    if (id == _UI_BAR_PROPERTY_VALUE)
        lv_bar_set_value(target, val, LV_ANIM_OFF);
}

void _ui_basic_set_property(lv_obj_t *target, int id, int val)
{
    if (id == _UI_BASIC_PROPERTY_POSITION_X)
        lv_obj_set_x(target, val);
    if (id == _UI_BASIC_PROPERTY_POSITION_Y)
        lv_obj_set_y(target, val);
    if (id == _UI_BASIC_PROPERTY_WIDTH)
        lv_obj_set_width(target, val);
    if (id == _UI_BASIC_PROPERTY_HEIGHT)
        lv_obj_set_height(target, val);
}

void _ui_dropdown_set_property(lv_obj_t *target, int id, int val)
{
    if (id == _UI_DROPDOWN_PROPERTY_SELECTED)
        lv_dropdown_set_selected(target, val);
}

void _ui_image_set_property(lv_obj_t *target, int id, uint8_t *val)
{
    if (id == _UI_IMAGE_PROPERTY_IMAGE)
        lv_img_set_src(target, val);
}

void _ui_label_set_property(lv_obj_t *target, int id, const char *val)
{
    if (id == _UI_LABEL_PROPERTY_TEXT)
        lv_label_set_text(target, val);
}

void _ui_roller_set_property(lv_obj_t *target, int id, int val)
{
    if (id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM)
        lv_roller_set_selected(target, val, LV_ANIM_ON);
    if (id == _UI_ROLLER_PROPERTY_SELECTED)
        lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

void _ui_slider_set_property(lv_obj_t *target, int id, int val)
{
    if (id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM)
        lv_slider_set_value(target, val, LV_ANIM_ON);
    if (id == _UI_SLIDER_PROPERTY_VALUE)
        lv_slider_set_value(target, val, LV_ANIM_OFF);
}
