// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"              // This should include lvgl.h and other necessary headers
#include "ui_modern_theme.h" // DEADEYE theme support
// Explicitly include headers for pages it navigates to, ensuring declarations are seen
#include "ui_Options_Page.h"
#include "ui_Shot_Counter_Page.h"
#include "ui_Competition_Page.h" // Ensures this file sees ui_Competition_Page and _screen_init

// --- Definitions for global UI object pointers for this screen ---
lv_obj_t *ui_Stage_Timer_Page;
lv_obj_t *ui_StageTimerPageTitleLabel;
lv_obj_t *ui_Page4HomeBTN;
lv_obj_t *ui_Page4HomeBTN1;
lv_obj_t *ui_Page4PrevBTN;
lv_obj_t *ui_Page4PrevBTN1;
lv_obj_t *ui_Page4NextBTN;
lv_obj_t *ui_Page4NextBTN1;

// New UI Element Objects for Stage Timer
lv_obj_t *ui_StageTimerDisplayValueLabel;
lv_obj_t *ui_StageTimerAddButton;
lv_obj_t *ui_StageTimerAddLabel;
lv_obj_t *ui_StageTimerSubButton;
lv_obj_t *ui_StageTimerSubLabel;
lv_obj_t *ui_StageTimerResetButton;
lv_obj_t *ui_StageTimerResetLabel;
lv_obj_t *ui_StageTimerStartPauseButton;
lv_obj_t *ui_StageTimerStartPauseLabel;

// --- Static variables for timer logic ---
#define DEFAULT_STAGE_TIME_SECONDS (5 * 60)
#define MAX_STAGE_TIME_SECONDS (60 * 60 - 1)
#define MIN_STAGE_TIME_SECONDS 0
#define TIME_ADJUST_INCREMENT_SECONDS 60

static uint32_t current_set_time_seconds;
static uint32_t time_remaining_seconds;
static lv_timer_t *countdown_lv_timer = NULL;
static bool timer_is_running = false;

// Forward declaration for the update helper and other static functions
static void update_stage_time_display_label(void);
static void stage_timer_countdown_callback(lv_timer_t *timer_obj);
static void set_timer_controls_state(bool running);

// --- Functions for Competition Page to access Stage Timer data/actions ---
uint32_t ui_stage_timer_get_time_remaining_seconds(void)
{
    return time_remaining_seconds;
}

uint32_t ui_stage_timer_get_current_set_time_seconds(void)
{
    return current_set_time_seconds;
}

bool ui_stage_timer_is_timer_running(void)
{
    return timer_is_running;
}

void ui_stage_timer_start_timer_action(void)
{
    if (!timer_is_running && time_remaining_seconds > 0)
    {
        if (countdown_lv_timer == NULL)
        {
            countdown_lv_timer = lv_timer_create(stage_timer_countdown_callback, 1000, NULL);
        }
        else
        {
            lv_timer_resume(countdown_lv_timer);
        }
        timer_is_running = true;
        if (ui_StageTimerStartPauseLabel)
        {
            lv_label_set_text(ui_StageTimerStartPauseLabel, "Pause");
        }
        set_timer_controls_state(true);
    }
}

void ui_stage_timer_pause_timer_action(void)
{
    if (timer_is_running)
    {
        if (countdown_lv_timer)
        {
            lv_timer_pause(countdown_lv_timer);
        }
        timer_is_running = false;
        if (ui_StageTimerStartPauseLabel)
        {
            lv_label_set_text(ui_StageTimerStartPauseLabel, "Resume");
        }
    }
}

void ui_stage_timer_reset_timer_to_set_time_action(void)
{
    if (countdown_lv_timer)
    {
        lv_timer_del(countdown_lv_timer);
        countdown_lv_timer = NULL;
    }
    timer_is_running = false;
    time_remaining_seconds = current_set_time_seconds;
    update_stage_time_display_label();
    if (ui_StageTimerStartPauseLabel)
    {
        lv_label_set_text(ui_StageTimerStartPauseLabel, "Start");
    }
    set_timer_controls_state(false);
}

// --- Event functions for existing navigation buttons ---
void ui_event_Page4HomeBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page4PrevBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Shot_Counter_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Shot_Counter_Page_screen_init);
    }
}

void ui_event_Page4NextBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Competition_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Competition_Page_screen_init);
    }
}

// --- Event functions for new stage timer buttons ---
void ui_event_StageTimerAddButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED && !timer_is_running)
    {
        uint32_t increment = ui_settings_get_time_adjust_increment();
        if (current_set_time_seconds <= MAX_STAGE_TIME_SECONDS - increment)
        {
            current_set_time_seconds += increment;
        }
        else
        {
            current_set_time_seconds = MAX_STAGE_TIME_SECONDS;
        }
        time_remaining_seconds = current_set_time_seconds;
        update_stage_time_display_label();
    }
}

void ui_event_StageTimerSubButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED && !timer_is_running)
    {
        uint32_t increment = ui_settings_get_time_adjust_increment();
        if (current_set_time_seconds >= MIN_STAGE_TIME_SECONDS + increment)
        {
            current_set_time_seconds -= increment;
        }
        else
        {
            current_set_time_seconds = MIN_STAGE_TIME_SECONDS;
        }
        time_remaining_seconds = current_set_time_seconds;
        update_stage_time_display_label();
    }
}

void ui_event_StageTimerResetButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        if (countdown_lv_timer)
        {
            lv_timer_del(countdown_lv_timer);
            countdown_lv_timer = NULL;
        }
        timer_is_running = false;
        time_remaining_seconds = current_set_time_seconds;
        update_stage_time_display_label();
        if (ui_StageTimerStartPauseLabel)
        {
            lv_label_set_text(ui_StageTimerStartPauseLabel, "Start");
        }
        set_timer_controls_state(false);
    }
}

void ui_event_StageTimerStartPauseButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        if (!timer_is_running)
        {
            if (time_remaining_seconds > 0)
            {
                if (countdown_lv_timer == NULL)
                {
                    countdown_lv_timer = lv_timer_create(stage_timer_countdown_callback, 1000, NULL);
                }
                else
                {
                    lv_timer_resume(countdown_lv_timer);
                }
                timer_is_running = true;
                if (ui_StageTimerStartPauseLabel)
                {
                    lv_label_set_text(ui_StageTimerStartPauseLabel, "Pause");
                }
                set_timer_controls_state(true);
            }
        }
        else
        {
            if (countdown_lv_timer)
            {
                lv_timer_pause(countdown_lv_timer);
            }
            timer_is_running = false;
            if (ui_StageTimerStartPauseLabel)
            {
                lv_label_set_text(ui_StageTimerStartPauseLabel, "Resume");
            }
        }
    }
}

// --- Helper function to update the timer display label ---
static void update_stage_time_display_label(void)
{
    if (ui_StageTimerDisplayValueLabel)
    {
        uint32_t minutes = time_remaining_seconds / 60;
        uint32_t seconds = time_remaining_seconds % 60;
        char buf[8]; // Increased buffer size for safety
        int result = lv_snprintf(buf, sizeof(buf), "%02u:%02u", minutes, seconds);
        if (result >= 0 && result < sizeof(buf))
        {
            lv_label_set_text(ui_StageTimerDisplayValueLabel, buf);
        }
    }
}

// --- LVGL Timer Callback ---
static void stage_timer_countdown_callback(lv_timer_t *timer_obj)
{
    (void)timer_obj;

    if (time_remaining_seconds > 0)
    {
        time_remaining_seconds--;
        update_stage_time_display_label();
    }
    else
    {
        // Timer finished - clean up
        if (countdown_lv_timer)
        {
            lv_timer_del(countdown_lv_timer);
            countdown_lv_timer = NULL;
        }
        timer_is_running = false;
        time_remaining_seconds = 0;
        update_stage_time_display_label();
        if (ui_StageTimerStartPauseLabel)
        {
            lv_label_set_text(ui_StageTimerStartPauseLabel, "Start");
        }
        set_timer_controls_state(false);
    }
}

// --- Helper to enable/disable timer adjustment buttons ---
static void set_timer_controls_state(bool running)
{
    if (ui_StageTimerAddButton && ui_StageTimerSubButton)
    {
        if (running)
        {
            lv_obj_add_state(ui_StageTimerAddButton, LV_STATE_DISABLED);
            lv_obj_add_state(ui_StageTimerSubButton, LV_STATE_DISABLED);
        }
        else
        {
            lv_obj_clear_state(ui_StageTimerAddButton, LV_STATE_DISABLED);
            lv_obj_clear_state(ui_StageTimerSubButton, LV_STATE_DISABLED);
        }
    }
}

// --- Build functions ---
void ui_Stage_Timer_Page_screen_init(void)
{
    // Initialize timer values from settings
    current_set_time_seconds = ui_settings_get_default_stage_time();
    time_remaining_seconds = current_set_time_seconds;

    ui_Stage_Timer_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Stage_Timer_Page, LV_OBJ_FLAG_SCROLLABLE);

    // Apply DEADEYE theme
    ui_modern_theme_apply_page_background(ui_Stage_Timer_Page);

    ui_StageTimerPageTitleLabel = lv_label_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_StageTimerPageTitleLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StageTimerPageTitleLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StageTimerPageTitleLabel, 0);
    lv_obj_set_y(ui_StageTimerPageTitleLabel, -125);
    lv_obj_set_align(ui_StageTimerPageTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StageTimerPageTitleLabel, "DEADEYE STAGE TIMER");
    ui_modern_theme_apply_title_style(ui_StageTimerPageTitleLabel);

    ui_StageTimerDisplayValueLabel = lv_label_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_StageTimerDisplayValueLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StageTimerDisplayValueLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StageTimerDisplayValueLabel, 0);
    lv_obj_set_y(ui_StageTimerDisplayValueLabel, -45);
    lv_obj_set_align(ui_StageTimerDisplayValueLabel, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_StageTimerDisplayValueLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_modern_theme_apply_primary_text_style(ui_StageTimerDisplayValueLabel);

    time_remaining_seconds = current_set_time_seconds;
    update_stage_time_display_label();

    ui_StageTimerSubButton = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_StageTimerSubButton, 50);
    lv_obj_set_height(ui_StageTimerSubButton, 30);
    lv_obj_align_to(ui_StageTimerSubButton, ui_StageTimerDisplayValueLabel, LV_ALIGN_OUT_LEFT_MID, 15, 135);
    lv_obj_add_flag(ui_StageTimerSubButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_StageTimerSubButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_StageTimerSubButton);

    ui_StageTimerSubLabel = lv_label_create(ui_StageTimerSubButton);
    lv_obj_set_align(ui_StageTimerSubLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StageTimerSubLabel, "-");

    ui_StageTimerAddButton = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_StageTimerAddButton, 50);
    lv_obj_set_height(ui_StageTimerAddButton, 30);
    lv_obj_align_to(ui_StageTimerAddButton, ui_StageTimerDisplayValueLabel, LV_ALIGN_OUT_RIGHT_MID, -15, 135);
    lv_obj_add_flag(ui_StageTimerAddButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_StageTimerAddButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_StageTimerAddButton);

    ui_StageTimerAddLabel = lv_label_create(ui_StageTimerAddButton);
    lv_obj_set_align(ui_StageTimerAddLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StageTimerAddLabel, "+");

    ui_StageTimerResetButton = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_StageTimerResetButton, 50);
    lv_obj_set_height(ui_StageTimerResetButton, 30);
    lv_obj_set_x(ui_StageTimerResetButton, 0);
    lv_obj_set_y(ui_StageTimerResetButton, 90);
    lv_obj_set_align(ui_StageTimerResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StageTimerResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_StageTimerResetButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_StageTimerResetButton);

    ui_StageTimerResetLabel = lv_label_create(ui_StageTimerResetButton);
    lv_obj_set_align(ui_StageTimerResetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StageTimerResetLabel, "Reset");

    ui_StageTimerStartPauseButton = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_StageTimerStartPauseButton, 50);
    lv_obj_set_height(ui_StageTimerStartPauseButton, 30);
    lv_obj_set_x(ui_StageTimerStartPauseButton, 0);
    lv_obj_set_y(ui_StageTimerStartPauseButton, 55);
    lv_obj_set_align(ui_StageTimerStartPauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StageTimerStartPauseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_StageTimerStartPauseButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_StageTimerStartPauseButton);

    ui_StageTimerStartPauseLabel = lv_label_create(ui_StageTimerStartPauseButton);
    lv_obj_set_align(ui_StageTimerStartPauseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StageTimerStartPauseLabel, "Start");

    const lv_coord_t nav_btn_y_offset = 125;

    ui_Page4HomeBTN = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_Page4HomeBTN, 50);
    lv_obj_set_height(ui_Page4HomeBTN, 25);
    lv_obj_set_x(ui_Page4HomeBTN, -60);
    lv_obj_set_y(ui_Page4HomeBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page4HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page4HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page4HomeBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page4HomeBTN);

    ui_Page4HomeBTN1 = lv_label_create(ui_Page4HomeBTN);
    lv_obj_set_align(ui_Page4HomeBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page4HomeBTN1, "HOME");

    ui_Page4PrevBTN = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_Page4PrevBTN, 50);
    lv_obj_set_height(ui_Page4PrevBTN, 25);
    lv_obj_set_x(ui_Page4PrevBTN, 0);
    lv_obj_set_y(ui_Page4PrevBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page4PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page4PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page4PrevBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page4PrevBTN);

    ui_Page4PrevBTN1 = lv_label_create(ui_Page4PrevBTN);
    lv_obj_set_align(ui_Page4PrevBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page4PrevBTN1, "PREV");
    lv_label_set_text(ui_Page4PrevBTN1, "PREV");

    ui_Page4NextBTN = lv_btn_create(ui_Stage_Timer_Page);
    lv_obj_set_width(ui_Page4NextBTN, 50);
    lv_obj_set_height(ui_Page4NextBTN, 25);
    lv_obj_set_x(ui_Page4NextBTN, 60);
    lv_obj_set_y(ui_Page4NextBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page4NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page4NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page4NextBTN, LV_OBJ_FLAG_SCROLLABLE);

    ui_Page4NextBTN1 = lv_label_create(ui_Page4NextBTN);
    lv_obj_set_align(ui_Page4NextBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page4NextBTN1, "NEXT");

    lv_obj_add_event_cb(ui_Page4HomeBTN, ui_event_Page4HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page4PrevBTN, ui_event_Page4PrevBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page4NextBTN, ui_event_Page4NextBTN, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_StageTimerAddButton, ui_event_StageTimerAddButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StageTimerSubButton, ui_event_StageTimerSubButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StageTimerResetButton, ui_event_StageTimerResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StageTimerStartPauseButton, ui_event_StageTimerStartPauseButton, LV_EVENT_ALL, NULL);

    set_timer_controls_state(false);
    update_stage_time_display_label();
}

void ui_Stage_Timer_Page_screen_destroy(void)
{
    if (countdown_lv_timer)
    {
        lv_timer_del(countdown_lv_timer);
        countdown_lv_timer = NULL;
    }
    timer_is_running = false;

    if (ui_Stage_Timer_Page)
    {
        lv_obj_del(ui_Stage_Timer_Page);
    }

    ui_Stage_Timer_Page = NULL;
    ui_StageTimerPageTitleLabel = NULL;
    ui_Page4HomeBTN = NULL;
    ui_Page4HomeBTN1 = NULL;
    ui_Page4PrevBTN = NULL;
    ui_Page4PrevBTN1 = NULL;
    ui_Page4NextBTN = NULL;
    ui_Page4NextBTN1 = NULL;

    ui_StageTimerDisplayValueLabel = NULL;
    ui_StageTimerAddButton = NULL;
    ui_StageTimerAddLabel = NULL;
    ui_StageTimerSubButton = NULL;
    ui_StageTimerSubLabel = NULL;
    ui_StageTimerResetButton = NULL;
    ui_StageTimerResetLabel = NULL;
    ui_StageTimerStartPauseButton = NULL;
    ui_StageTimerStartPauseLabel = NULL;
}
