// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"              // This should include lvgl.h and other necessary headers
#include "ui_modern_theme.h" // DEADEYE theme support
#include "ui_Options_Page.h"
#include "ui_Shot_Counter_Page.h"
#include "ui_Competition_Page.h"

// --- Definitions for global UI object pointers for this screen ---
lv_obj_t *ui_Stage_Timer_Page = nullptr;
lv_obj_t *ui_StageTimerPageTitleLabel = nullptr;
lv_obj_t *ui_Page4HomeBTN = nullptr;
lv_obj_t *ui_Page4HomeBTN1 = nullptr;
lv_obj_t *ui_Page4PrevBTN = nullptr;
lv_obj_t *ui_Page4PrevBTN1 = nullptr;
lv_obj_t *ui_Page4NextBTN = nullptr;
lv_obj_t *ui_Page4NextBTN1 = nullptr;

// New UI Element Objects for Stage Timer
lv_obj_t *ui_StageTimerDisplayValueLabel = nullptr;
lv_obj_t *ui_StageTimerAddButton = nullptr;
lv_obj_t *ui_StageTimerAddLabel = nullptr;
lv_obj_t *ui_StageTimerSubButton = nullptr;
lv_obj_t *ui_StageTimerSubLabel = nullptr;
lv_obj_t *ui_StageTimerResetButton = nullptr;
lv_obj_t *ui_StageTimerResetLabel = nullptr;
lv_obj_t *ui_StageTimerStartPauseButton = nullptr;
lv_obj_t *ui_StageTimerStartPauseLabel = nullptr;

// --- Static variables for timer logic ---
#define DEFAULT_STAGE_TIME_SECONDS (5 * 60)
#define MAX_STAGE_TIME_SECONDS (60 * 60 - 1)
#define MIN_STAGE_TIME_SECONDS 0
#define TIME_ADJUST_INCREMENT_SECONDS 60

static uint32_t current_set_time_seconds;
static uint32_t time_remaining_seconds;
static lv_timer_t *countdown_lv_timer = nullptr;
static bool timer_is_running = false;

// Forward declaration for the update helper and other static functions
static void update_stage_time_display_label(void);
static void stage_timer_countdown_callback(lv_timer_t *timer_obj);
static void set_timer_controls_state(bool running);

// --- Functions for Competition Page to access Stage Timer data/actions ---
uint32_t ui_stage_timer_get_time_remaining_seconds(void)
{
    return time_remaining_seconds;
}

uint32_t ui_stage_timer_get_current_set_time_seconds(void)
{
    return current_set_time_seconds;
}
// ...existing code for the rest of the file...
