// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <cstdlib> // for std::malloc, std::free if needed

// COMPONENT Page4

lv_obj_t *ui_Page4_create(lv_obj_t *comp_parent)
{
    lv_obj_t *cui_Page4;
    cui_Page4 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Page4, 100);
    lv_obj_set_height(cui_Page4, 25);
    lv_obj_set_x(cui_Page4, 0);
    lv_obj_set_y(cui_Page4, 50);
    lv_obj_set_align(cui_Page4, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Page4, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(cui_Page4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    lv_obj_t *cui_StageTimerBTN;
    cui_StageTimerBTN = lv_label_create(cui_Page4);
    lv_obj_set_width(cui_StageTimerBTN, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_StageTimerBTN, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_StageTimerBTN, LV_ALIGN_CENTER);
    lv_label_set_text(cui_StageTimerBTN, "Stage Timer");

    lv_obj_t **children = static_cast<lv_obj_t **>(lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PAGE4_NUM));
    if (children)
    {
        children[UI_COMP_PAGE4_PAGE4] = cui_Page4;
        children[UI_COMP_PAGE4_STAGETIMERBTN] = cui_StageTimerBTN;
        lv_obj_add_event_cb(cui_Page4, get_component_child_event_cb, (lv_event_code_t)LV_EVENT_GET_COMP_CHILD, children);
        lv_obj_add_event_cb(cui_Page4, del_component_child_event_cb, LV_EVENT_DELETE, children);
    }
    ui_comp_Page4_create_hook(cui_Page4);
    return cui_Page4;
}
