// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "ui_comp.h"

#include <cstdint>

uint32_t LV_EVENT_GET_COMP_CHILD;

struct ui_comp_get_child_t {
    uint32_t child_idx;
    lv_obj_t * child;
};

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx)
{
    ui_comp_get_child_t info;
    info.child = nullptr;
    info.child_idx = child_idx;
    lv_event_send(comp, (lv_event_code_t)LV_EVENT_GET_COMP_CHILD, &info);
    return info.child;
}

void get_component_child_event_cb(lv_event_t * e)
{
    lv_obj_t ** c = static_cast<lv_obj_t **>(lv_event_get_user_data(e));
    ui_comp_get_child_t * info = static_cast<ui_comp_get_child_t *>(lv_event_get_param(e));
    info->child = c[info->child_idx];
}

void del_component_child_event_cb(lv_event_t * e)
{
    lv_obj_t ** c = static_cast<lv_obj_t **>(lv_event_get_user_data(e));
    lv_mem_free(c);
}
