// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11        if (time_sec > 0 && time_sec <= ui_settings_get_time_warning_threshold()) {// Project name: SquareLine_Project

#include "ui.h"
#include "ui_modern_theme.h" // DEADEYE theme support
#include "ui_Shot_Counter_Page.h"
#include "ui_Stage_Timer_Page.h"
#include <stdio.h>
#include <math.h>

// --- Color threshold constants ---
#define BUBBLE_LEVEL_THRESHOLD_GREEN 3.0f
#define BUBBLE_LEVEL_THRESHOLD_YELLOW 8.0f
#define TIME_WARNING_THRESHOLD_SECONDS 30

// --- Bubble Level Definitions ---
#define LEVEL_CANVAS_WIDTH 200
#define LEVEL_CANVAS_HEIGHT 40
#define TUBE_WIDTH (LEVEL_CANVAS_WIDTH - 10)
#define TUBE_HEIGHT (LEVEL_CANVAS_HEIGHT - 10)
#define TUBE_BORDER_RADIUS 8
#define BUBBLE_HEIGHT (TUBE_HEIGHT - 2)
#define BUBBLE_WIDTH (BUBBLE_HEIGHT + 12)
#define MAX_ROLL_ANGLE 30.0f

// --- Global UI object pointers for Competition Page ---
lv_obj_t *ui_Competition_Page;
lv_obj_t *ui_CompPageLabel;

// Original Navigation buttons
lv_obj_t *ui_Page5HomeBTN;
lv_obj_t *ui_Page5HomeBTN1;
lv_obj_t *ui_Page5PrevBTN;
lv_obj_t *ui_Page5PrevBTN1;
lv_obj_t *ui_Page5NextBTN;
lv_obj_t *ui_Page5NextBTN1;

// New UI Elements
lv_obj_t *ui_CompPageTimeStaticLabel;
lv_obj_t *ui_CompPageTimeValueLabel;
lv_obj_t *ui_CompPageShotsStaticLabel;
lv_obj_t *ui_CompPageShotsValueLabel;
lv_obj_t *ui_CompPageStartButton;
lv_obj_t *ui_CompPageStartButtonLabel;
lv_obj_t *ui_CompPageResetButton;
lv_obj_t *ui_CompPageResetButtonLabel;

// Bubble Level UI Elements
static lv_obj_t *ui_BubbleLevelCanvas = NULL;
static lv_obj_t *ui_RollAngleLabel = NULL;
static lv_timer_t *ui_level_update_timer = NULL;

// LVGL Timer for live data updates on this page
static lv_timer_t *competition_page_data_refresh_timer = NULL;

// --- Colors for the Bubble Level ---
static lv_color_t color_page_bg_bubble;
static lv_color_t color_tube_bg_bubble;
static lv_color_t color_bubble_green;
static lv_color_t color_bubble_yellow;
static lv_color_t color_bubble_red;
static lv_color_t color_text_roll_label;
static lv_color_t color_tube_marking_bubble;

// Define a default background color (e.g. black for a dark theme, or use theme default)
static lv_color_t default_competition_page_bgcolor;

// --- Forward declarations for static functions ---
static void competition_page_refresh_timer_cb(lv_timer_t *timer);
static void competition_page_visibility_event_cb(lv_event_t *e); // For managing timer
static void draw_bubble_level_on_canvas(float roll_angle_deg);
static void level_update_timer_cb(lv_timer_t *timer);

// --- Public function to update displayed data (callable) ---
void ui_Competition_Page_update_live_data_display(void)
{
    uint32_t time_sec = 0; // Initialize to ensure it has a value

    // Update Time Display
    if (ui_CompPageTimeValueLabel)
    {
        time_sec = ui_stage_timer_get_time_remaining_seconds();
        uint32_t minutes = time_sec / 60;
        uint32_t seconds = time_sec % 60;
        char buf[8]; // "MM:SS\0"
        int result = lv_snprintf(buf, sizeof(buf), "%02u:%02u", minutes, seconds);
        if (result >= 0 && result < sizeof(buf))
        {
            lv_label_set_text(ui_CompPageTimeValueLabel, buf);
        }
    }

    // Update Shots Display
    if (ui_CompPageShotsValueLabel)
    {
        int shots = ui_shot_counter_get_shots_remaining();
        char buf[8]; // Increased buffer size for safety
        int result = lv_snprintf(buf, sizeof(buf), "%d", shots);
        if (result >= 0 && result < sizeof(buf))
        {
            lv_label_set_text(ui_CompPageShotsValueLabel, buf);
        }
    }

    // Update Start/Pause/Resume Button Label
    if (ui_CompPageStartButtonLabel)
    {
        if (ui_stage_timer_is_timer_running())
        {
            lv_label_set_text(ui_CompPageStartButtonLabel, "Pause");
        }
        else
        {
            if (time_sec > 0 && time_sec < ui_stage_timer_get_current_set_time_seconds())
            {
                lv_label_set_text(ui_CompPageStartButtonLabel, "Resume");
            }
            else
            {
                lv_label_set_text(ui_CompPageStartButtonLabel, "Start");
            }
        }
    }

    // Update background color based on time remaining
    if (ui_Competition_Page)
    {
        if (time_sec > 0 && time_sec <= TIME_WARNING_THRESHOLD_SECONDS)
        {
            lv_obj_set_style_bg_color(ui_Competition_Page, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        else
        {
            lv_color_t current_bg = lv_obj_get_style_bg_color(ui_Competition_Page, LV_PART_MAIN);
            lv_color_t target_bg = (default_competition_page_bgcolor.full != 0) ? default_competition_page_bgcolor : lv_color_black();

            if (current_bg.full != target_bg.full)
            {
                lv_obj_set_style_bg_color(ui_Competition_Page, target_bg, LV_PART_MAIN | LV_STATE_DEFAULT);
            }
        }
    }
}

// --- Event functions for original navigation buttons ---
void ui_event_Page5HomeBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page5PrevBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Stage_Timer_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Stage_Timer_Page_screen_init);
    }
}

void ui_event_Page5NextBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Options_Page_screen_init);
    }
}

// --- Event functions for new Competition Page buttons ---
void ui_event_CompPageStartButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        if (ui_stage_timer_is_timer_running())
        {
            ui_stage_timer_pause_timer_action();
        }
        else
        {
            if (ui_stage_timer_get_time_remaining_seconds() > 0)
            {
                ui_stage_timer_start_timer_action();
            }
        }
        ui_Competition_Page_update_live_data_display();
    }
}

void ui_event_CompPageResetButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        ui_stage_timer_reset_timer_to_set_time_action();
        ui_shot_counter_reset_to_set_count();
        ui_Competition_Page_update_live_data_display();
    }
}

// --- Bubble Level Helper Functions (Copied from ui_Bubble_Level_Page.c) ---

static void draw_bubble_level_on_canvas(float roll_angle_deg)
{
    if (!ui_BubbleLevelCanvas || !lv_obj_is_valid(ui_BubbleLevelCanvas))
    {
        return;
    }

    float display_angle = roll_angle_deg;
    if (display_angle > MAX_ROLL_ANGLE)
        display_angle = MAX_ROLL_ANGLE;
    if (display_angle < -MAX_ROLL_ANGLE)
        display_angle = -MAX_ROLL_ANGLE;

    lv_canvas_fill_bg(ui_BubbleLevelCanvas, color_page_bg_bubble, LV_OPA_COVER);

    lv_draw_rect_dsc_t tube_dsc;
    lv_draw_rect_dsc_init(&tube_dsc);
    tube_dsc.bg_color = color_tube_bg_bubble;
    tube_dsc.radius = TUBE_BORDER_RADIUS;
    int32_t tube_draw_x = (LEVEL_CANVAS_WIDTH - TUBE_WIDTH) / 2;
    int32_t tube_draw_y = (LEVEL_CANVAS_HEIGHT - TUBE_HEIGHT) / 2;
    lv_canvas_draw_rect(ui_BubbleLevelCanvas, tube_draw_x, tube_draw_y, TUBE_WIDTH, TUBE_HEIGHT, &tube_dsc);

    lv_draw_rect_dsc_t mark_rect_dsc;
    lv_draw_rect_dsc_init(&mark_rect_dsc);
    mark_rect_dsc.bg_color = color_tube_marking_bubble;
    lv_canvas_draw_rect(ui_BubbleLevelCanvas,
                        tube_draw_x + TUBE_WIDTH / 2 - 1,
                        tube_draw_y + 2,
                        2,
                        TUBE_HEIGHT - 4,
                        &mark_rect_dsc);

    int32_t bubble_travel_range_px = TUBE_WIDTH - BUBBLE_WIDTH;
    if (bubble_travel_range_px < 0)
        bubble_travel_range_px = 0;

    float normalized_pos = (display_angle + MAX_ROLL_ANGLE) / (2.0f * MAX_ROLL_ANGLE);
    int32_t bubble_offset_in_tube = (int32_t)(normalized_pos * bubble_travel_range_px);

    int32_t bubble_draw_x = tube_draw_x + bubble_offset_in_tube;
    int32_t bubble_draw_y = tube_draw_y + (TUBE_HEIGHT - BUBBLE_HEIGHT) / 2;

    lv_color_t current_bubble_color;
    float abs_actual_angle = fabsf(roll_angle_deg);

    if (abs_actual_angle <= ui_settings_get_bubble_green_threshold())
    {
        current_bubble_color = color_bubble_green;
    }
    else if (abs_actual_angle <= ui_settings_get_bubble_yellow_threshold())
    {
        current_bubble_color = color_bubble_yellow;
    }
    else
    {
        current_bubble_color = color_bubble_red;
    }

    lv_draw_rect_dsc_t bubble_dsc;
    lv_draw_rect_dsc_init(&bubble_dsc);
    bubble_dsc.bg_color = current_bubble_color;
    bubble_dsc.radius = BUBBLE_HEIGHT / 2;
    lv_canvas_draw_rect(ui_BubbleLevelCanvas,
                        bubble_draw_x,
                        bubble_draw_y,
                        BUBBLE_WIDTH,
                        BUBBLE_HEIGHT,
                        &bubble_dsc);
}

static void level_update_timer_cb(lv_timer_t *timer)
{
    (void)timer;

    if (!ui_Competition_Page || !lv_obj_is_valid(ui_Competition_Page) ||
        !ui_RollAngleLabel || !lv_obj_is_valid(ui_RollAngleLabel) ||
        !ui_BubbleLevelCanvas || !lv_obj_is_valid(ui_BubbleLevelCanvas))
    {
        // Stop the timer if any objects are invalid
        if (ui_level_update_timer)
        {
            lv_timer_del(ui_level_update_timer);
            ui_level_update_timer = NULL;
        }
        return;
    }

    float current_roll = get_qmi8658_roll_degrees();

    char angle_text_buf[16];
    snprintf(angle_text_buf, sizeof(angle_text_buf), "%.0f°", current_roll);
    lv_label_set_text(ui_RollAngleLabel, angle_text_buf);

    draw_bubble_level_on_canvas(current_roll);
}

// --- LVGL Timer Callback for Competition Page live updates ---
static void competition_page_refresh_timer_cb(lv_timer_t *timer)
{
    LV_UNUSED(timer);
    ui_Competition_Page_update_live_data_display();
}

// --- Event handler for screen load/unload to manage the refresh timer ---
static void competition_page_visibility_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *screen = lv_event_get_target(e);

    if (screen == ui_Competition_Page)
    {
        if (code == LV_EVENT_SCREEN_LOADED)
        {
            // Start or resume data refresh timer
            if (competition_page_data_refresh_timer)
            {
                lv_timer_resume(competition_page_data_refresh_timer);
            }
            else
            {
                competition_page_data_refresh_timer = lv_timer_create(competition_page_refresh_timer_cb, 330, NULL);
            }

            // Start or resume level update timer
            if (ui_level_update_timer)
            {
                lv_timer_resume(ui_level_update_timer);
            }
            else
            {
                ui_level_update_timer = lv_timer_create(level_update_timer_cb, 250, NULL);
            }

            // Store default background color
            if (ui_Competition_Page)
            {
                default_competition_page_bgcolor = lv_obj_get_style_bg_color(ui_Competition_Page, LV_PART_MAIN);
            }
            ui_Competition_Page_update_live_data_display();
        }
        else if (code == LV_EVENT_SCREEN_UNLOADED)
        {
            // Pause timers instead of deleting them
            if (competition_page_data_refresh_timer)
            {
                lv_timer_pause(competition_page_data_refresh_timer);
            }
            if (ui_level_update_timer)
            {
                lv_timer_pause(ui_level_update_timer);
            }

            // Restore default background color
            if (ui_Competition_Page)
            {
                if (default_competition_page_bgcolor.full != 0)
                {
                    lv_obj_set_style_bg_color(ui_Competition_Page, default_competition_page_bgcolor, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                else
                {
                    lv_obj_set_style_bg_color(ui_Competition_Page, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
                }
            }
        }
    }
}

// --- New function to handle recoil event, called externally ---
void ui_competition_page_handle_recoil_event(void)
{
    bool timer_is_active = ui_stage_timer_is_timer_running();

    if (timer_is_active)
    {
        ui_shot_counter_decrement_shot();
        ui_Competition_Page_update_live_data_display();
    }
}

// --- Build function for Competition Page screen ---
void ui_Competition_Page_screen_init(void)
{
    ui_Competition_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Competition_Page, LV_OBJ_FLAG_SCROLLABLE);
    default_competition_page_bgcolor.full = 0;

    // Apply DEADEYE theme
    ui_modern_theme_apply_page_background(ui_Competition_Page);

    ui_CompPageLabel = lv_label_create(ui_Competition_Page);
    lv_obj_set_width(ui_CompPageLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_CompPageLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_CompPageLabel, 0);
    lv_obj_set_y(ui_CompPageLabel, -125);
    lv_obj_set_align(ui_CompPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompPageLabel, "DEADEYE COMPETITION");
    ui_modern_theme_apply_title_style(ui_CompPageLabel);

    ui_CompPageTimeStaticLabel = lv_label_create(ui_Competition_Page);
    lv_label_set_text(ui_CompPageTimeStaticLabel, "Time:");
    lv_obj_set_x(ui_CompPageTimeStaticLabel, -80);
    lv_obj_set_y(ui_CompPageTimeStaticLabel, -90);
    lv_obj_set_align(ui_CompPageTimeStaticLabel, LV_ALIGN_CENTER);
    ui_modern_theme_apply_secondary_text_style(ui_CompPageTimeStaticLabel);

    ui_CompPageTimeValueLabel = lv_label_create(ui_Competition_Page);
    lv_obj_set_width(ui_CompPageTimeValueLabel, 120);
    lv_obj_align_to(ui_CompPageTimeValueLabel, ui_CompPageTimeStaticLabel, LV_ALIGN_OUT_RIGHT_MID, 15, -5);
    lv_obj_set_style_text_font(ui_CompPageTimeValueLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_CompPageTimeValueLabel, "00:00");
    ui_modern_theme_apply_primary_text_style(ui_CompPageTimeValueLabel);

    ui_CompPageShotsStaticLabel = lv_label_create(ui_Competition_Page);
    lv_label_set_text(ui_CompPageShotsStaticLabel, "Shots:");
    lv_obj_set_x(ui_CompPageShotsStaticLabel, -80);
    lv_obj_set_y(ui_CompPageShotsStaticLabel, -50);
    lv_obj_set_align(ui_CompPageShotsStaticLabel, LV_ALIGN_CENTER);
    ui_modern_theme_apply_secondary_text_style(ui_CompPageShotsStaticLabel);

    ui_CompPageShotsValueLabel = lv_label_create(ui_Competition_Page);
    lv_obj_set_width(ui_CompPageShotsValueLabel, 80);
    lv_obj_align_to(ui_CompPageShotsValueLabel, ui_CompPageShotsStaticLabel, LV_ALIGN_OUT_RIGHT_MID, 50, -5);
    lv_obj_set_style_text_font(ui_CompPageShotsValueLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_CompPageShotsValueLabel, "0");
    ui_modern_theme_apply_primary_text_style(ui_CompPageShotsValueLabel);

    // --- Bubble Level Specific UI Initialization - DEADEYE Theme ---
    ui_modern_colors_t colors = ui_modern_colors;

    color_page_bg_bubble = colors.primary_dark;
    color_tube_bg_bubble = colors.primary_light;
    color_bubble_green = colors.accent_green;
    color_bubble_yellow = colors.warning_amber;
    color_bubble_red = colors.accent_red;
    color_text_roll_label = colors.text_primary;
    color_tube_marking_bubble = colors.text_secondary;

    ui_RollAngleLabel = lv_label_create(ui_Competition_Page);
    lv_label_set_text(ui_RollAngleLabel, "0°");
    lv_obj_set_style_text_color(ui_RollAngleLabel, color_text_roll_label, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_RollAngleLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_modern_theme_apply_secondary_text_style(ui_RollAngleLabel);
    lv_obj_align(ui_RollAngleLabel, LV_ALIGN_CENTER, 0, 40);

    ui_BubbleLevelCanvas = lv_canvas_create(ui_Competition_Page);
    static lv_color_t canvas_buffer[LV_CANVAS_BUF_SIZE_TRUE_COLOR(LEVEL_CANVAS_WIDTH, LEVEL_CANVAS_HEIGHT)];
    lv_canvas_set_buffer(ui_BubbleLevelCanvas, canvas_buffer, LEVEL_CANVAS_WIDTH, LEVEL_CANVAS_HEIGHT, LV_IMG_CF_TRUE_COLOR);
    lv_obj_align(ui_BubbleLevelCanvas, LV_ALIGN_CENTER, 0, 10);
    draw_bubble_level_on_canvas(0.0f);

    ui_CompPageStartButton = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_CompPageStartButton, 90);
    lv_obj_set_height(ui_CompPageStartButton, 40);
    lv_obj_set_x(ui_CompPageStartButton, -55);
    lv_obj_set_y(ui_CompPageStartButton, 80);
    lv_obj_set_align(ui_CompPageStartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompPageStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_CompPageStartButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_CompPageStartButton);

    ui_CompPageStartButtonLabel = lv_label_create(ui_CompPageStartButton);
    lv_obj_set_align(ui_CompPageStartButtonLabel, LV_ALIGN_CENTER);

    ui_CompPageResetButton = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_CompPageResetButton, 90);
    lv_obj_set_height(ui_CompPageResetButton, 40);
    lv_obj_set_x(ui_CompPageResetButton, 55);
    lv_obj_set_y(ui_CompPageResetButton, 80);
    lv_obj_set_align(ui_CompPageResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompPageResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_CompPageResetButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_CompPageResetButton);

    ui_CompPageResetButtonLabel = lv_label_create(ui_CompPageResetButton);
    lv_label_set_text(ui_CompPageResetButtonLabel, "Reset");
    lv_obj_set_align(ui_CompPageResetButtonLabel, LV_ALIGN_CENTER);

    const lv_coord_t nav_btn_y_offset = 125;

    ui_Page5HomeBTN = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_Page5HomeBTN, 50);
    lv_obj_set_height(ui_Page5HomeBTN, 25);
    lv_obj_set_x(ui_Page5HomeBTN, -60);
    lv_obj_set_y(ui_Page5HomeBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page5HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page5HomeBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page5HomeBTN);
    ui_Page5HomeBTN1 = lv_label_create(ui_Page5HomeBTN);
    lv_label_set_text(ui_Page5HomeBTN1, "HOME");
    lv_obj_set_align(ui_Page5HomeBTN1, LV_ALIGN_CENTER);

    ui_Page5PrevBTN = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_Page5PrevBTN, 50);
    lv_obj_set_height(ui_Page5PrevBTN, 25);
    lv_obj_set_x(ui_Page5PrevBTN, 0);
    lv_obj_set_y(ui_Page5PrevBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page5PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page5PrevBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page5PrevBTN);
    lv_obj_set_x(ui_Page5PrevBTN, 0);
    lv_obj_set_y(ui_Page5PrevBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page5PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page5PrevBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_Page5PrevBTN1 = lv_label_create(ui_Page5PrevBTN);
    lv_label_set_text(ui_Page5PrevBTN1, "PREV");
    lv_obj_set_align(ui_Page5PrevBTN1, LV_ALIGN_CENTER);

    ui_Page5NextBTN = lv_btn_create(ui_Competition_Page);
    lv_obj_set_width(ui_Page5NextBTN, 50);
    lv_obj_set_height(ui_Page5NextBTN, 25);
    lv_obj_set_x(ui_Page5NextBTN, 60);
    lv_obj_set_y(ui_Page5NextBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page5NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page5NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page5NextBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_Page5NextBTN1 = lv_label_create(ui_Page5NextBTN);
    lv_label_set_text(ui_Page5NextBTN1, "NEXT");
    lv_obj_set_align(ui_Page5NextBTN1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Page5HomeBTN, ui_event_Page5HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page5PrevBTN, ui_event_Page5PrevBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page5NextBTN, ui_event_Page5NextBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CompPageStartButton, ui_event_CompPageStartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CompPageResetButton, ui_event_CompPageResetButton, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Competition_Page, competition_page_visibility_event_cb, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_Competition_Page, competition_page_visibility_event_cb, LV_EVENT_SCREEN_UNLOADED, NULL);

    ui_Competition_Page_update_live_data_display();
}

void ui_Competition_Page_screen_destroy(void)
{
    if (competition_page_data_refresh_timer)
    {
        lv_timer_del(competition_page_data_refresh_timer);
        competition_page_data_refresh_timer = NULL;
    }

    if (ui_level_update_timer)
    {
        lv_timer_del(ui_level_update_timer);
        ui_level_update_timer = NULL;
    }

    if (ui_Competition_Page)
    {
        lv_obj_remove_event_cb_with_user_data(ui_Competition_Page, competition_page_visibility_event_cb, NULL);
        lv_obj_del(ui_Competition_Page);
    }

    ui_Competition_Page = NULL;
    ui_CompPageLabel = NULL;
    ui_Page5HomeBTN = NULL;
    ui_Page5HomeBTN1 = NULL;
    ui_Page5PrevBTN = NULL;
    ui_Page5PrevBTN1 = NULL;
    ui_Page5NextBTN = NULL;
    ui_Page5NextBTN1 = NULL;

    ui_CompPageTimeStaticLabel = NULL;
    ui_CompPageTimeValueLabel = NULL;
    ui_CompPageShotsStaticLabel = NULL;
    ui_CompPageShotsValueLabel = NULL;
    ui_CompPageStartButton = NULL;
    ui_CompPageStartButtonLabel = NULL;
    ui_CompPageResetButton = NULL;
    ui_CompPageResetButtonLabel = NULL;

    ui_BubbleLevelCanvas = NULL;
    ui_RollAngleLabel = NULL;
}