#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Artificial_Horizon_Page.cpp"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"                           // Should include lvgl.h and all other ui_*.h files
#include "ui_modern_theme.h"              // DEADEYE theme support
#include "ui_artificial_horizon_widget.h" // Our custom widget header

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Artificial_Horizon_Page = nullptr;
lv_obj_t *ui_ArtificialHorizonPageLabel = nullptr;
lv_obj_t *ui_Page2HomeBTN = nullptr;
lv_obj_t *ui_HomeBTN1 = nullptr;
lv_obj_t *ui_Page2PrevBTN = nullptr;
lv_obj_t *ui_Page2PrevBTN1 = nullptr;
lv_obj_t *ui_Page2NextBTN2 = nullptr; // Assuming this is the button object
lv_obj_t *ui_Page2NextBTN = nullptr;  // Assuming this is the label for the next button (as per your .h)
lv_obj_t *ui_Label5 = nullptr;        // A general label, perhaps a title or unused.

// CUSTOM VARIABLES for Artificial Horizon
lv_obj_t *uic_ArtificialHorizon = nullptr;             // The container object for the AHRS, declared in .h
static ui_ahrs_widget_t ahrs_data;           // Static data structure for our AHRS widget
static lv_timer_t *ahrs_update_timer = nullptr; // Timer for updating the AHRS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
// Event handler prototypes (these should be defined in ui_events.c or similar)
// extern void ui_event_Page2HomeBTN(lv_event_t * e);
// extern void ui_event_Page2PrevBTN(lv_event_t * e);
// extern void ui_event_Page2NextBTN2(lv_event_t * e); // Or whatever the correct event for next is

// Timer callback function to update the artificial horizon
static void update_artificial_horizon_widget_timer_cb(lv_timer_t *timer)
{
    // If you passed &ahrs_data as user_data to the timer:
    // ui_ahrs_widget_t* data = (ui_ahrs_widget_t*)timer->user_data;
    // update_artificial_horizon_widget(data);
    // Otherwise, if using the static global:
    update_artificial_horizon_widget(&ahrs_data);
}

///////////////////// SCREENS ////////////////////
void ui_Artificial_Horizon_Page_screen_init(void)
{
    ui_Artificial_Horizon_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Artificial_Horizon_Page, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // Apply DEADEYE theme
    ui_modern_style_page(ui_Artificial_Horizon_Page);
    // ...existing code for the rest of the file...
}
