#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Bubble_Level_Page.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BUBBLE_LEVEL_PAGE_H
#define UI_BUBBLE_LEVEL_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Bubble_Level_Page
extern void ui_Bubble_Level_Page_screen_init(void);
extern void ui_Bubble_Level_Page_screen_destroy(void);
extern lv_obj_t * ui_Bubble_Level_Page;
extern lv_obj_t * ui_BubbleLevelPageLabel;
extern void ui_event_Page1HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page1HomeBTN;
extern lv_obj_t * ui_Pg1HomeBTN;
extern void ui_event_Page1NextBTN1(lv_event_t * e);
extern lv_obj_t * ui_Page1NextBTN1;
extern lv_obj_t * ui_Page1NextBTN;
extern void ui_event_Page1PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page1PrevBTN;
extern lv_obj_t * ui_Page1PrevBTN1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

