#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_comp_page4.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_PAGE4_H
#define _UI_COMP_PAGE4_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Page4
#define UI_COMP_PAGE4_PAGE4 0
#define UI_COMP_PAGE4_STAGETIMERBTN 1
#define _UI_COMP_PAGE4_NUM 2
lv_obj_t * ui_Page4_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
