#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Competition_Page.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COMPETITION_PAGE_H
#define UI_COMPETITION_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h" // Or your main LVGL header if different

// SCREEN: ui_Competition_Page
extern lv_obj_t * ui_Competition_Page; // Global variable for the screen object
extern void ui_Competition_Page_screen_init(void);
extern void ui_Competition_Page_screen_destroy(void);

// UI Elements specific to Competition Page (if they need to be accessed externally)
extern lv_obj_t * ui_CompPageLabel;
// extern lv_obj_t * ui_CompPageTimeStaticLabel; // Typically not needed extern
// extern lv_obj_t * ui_CompPageTimeValueLabel;  // Typically not needed extern
// extern lv_obj_t * ui_CompPageShotsStaticLabel; // Typically not needed extern
// extern lv_obj_t * ui_CompPageShotsValueLabel; // Typically not needed extern
// extern lv_obj_t * ui_CompPageStartButton;     // Typically not needed extern
// extern lv_obj_t * ui_CompPageStartButtonLabel; // Typically not needed extern
// extern lv_obj_t * ui_CompPageResetButton;     // Typically not needed extern
// extern lv_obj_t * ui_CompPageResetButtonLabel; // Typically not needed extern

// Navigation button objects declared in ui_Competition_Page.c are made extern here
// if they were originally created by SquareLine Studio for this page.
// If these are generic navigation elements handled by a shared component,
// their declarations might be elsewhere or not needed here.
// Based on original files, assuming these were specific to this page's SLS design.
extern lv_obj_t * ui_Page5HomeBTN; 
extern lv_obj_t * ui_Page5HomeBTN1;
extern lv_obj_t * ui_Page5PrevBTN;
extern lv_obj_t * ui_Page5PrevBTN1;
extern lv_obj_t * ui_Page5NextBTN;
extern lv_obj_t * ui_Page5NextBTN1;

// Event Handlers that might be called (though usually they are static to the .c file)
// If _ui_screen_change is used, these specific event handlers are usually not extern.
// But matching the original structure from your provided files:
extern void ui_event_Page5HomeBTN(lv_event_t * e);
extern void ui_event_Page5PrevBTN(lv_event_t * e);
extern void ui_event_Page5NextBTN(lv_event_t * e);
extern void ui_event_CompPageStartButton(lv_event_t * e);
extern void ui_event_CompPageResetButton(lv_event_t * e);


// Public functions for Competition Page logic
extern void ui_Competition_Page_update_live_data_display(void);
extern void ui_competition_page_handle_recoil_event(void);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*UI_COMPETITION_PAGE_H*/
