#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Competition_Page.cpp"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_modern_theme.h" // DEADEYE theme support
#include "ui_Shot_Counter_Page.h"
#include "ui_Stage_Timer_Page.h"
#include <cstdio>
#include <cmath>

// --- Color threshold constants ---
#define BUBBLE_LEVEL_THRESHOLD_GREEN 3.0f
#define BUBBLE_LEVEL_THRESHOLD_YELLOW 8.0f
#define TIME_WARNING_THRESHOLD_SECONDS 30

// --- Bubble Level Definitions ---
#define LEVEL_CANVAS_WIDTH 200
#define LEVEL_CANVAS_HEIGHT 40
#define TUBE_WIDTH (LEVEL_CANVAS_WIDTH - 10)
#define TUBE_HEIGHT (LEVEL_CANVAS_HEIGHT - 10)
#define TUBE_BORDER_RADIUS 8
#define BUBBLE_HEIGHT (TUBE_HEIGHT - 2)
#define BUBBLE_WIDTH (BUBBLE_HEIGHT + 12)
#define MAX_ROLL_ANGLE 30.0f

// --- Global UI object pointers for Competition Page ---
lv_obj_t *ui_Competition_Page = nullptr;
lv_obj_t *ui_CompPageLabel = nullptr;

// Original Navigation buttons
lv_obj_t *ui_Page5HomeBTN = nullptr;
lv_obj_t *ui_Page5HomeBTN1 = nullptr;
lv_obj_t *ui_Page5PrevBTN = nullptr;
lv_obj_t *ui_Page5PrevBTN1 = nullptr;
lv_obj_t *ui_Page5NextBTN = nullptr;
lv_obj_t *ui_Page5NextBTN1 = nullptr;

// New UI Elements
lv_obj_t *ui_CompPageTimeStaticLabel = nullptr;
lv_obj_t *ui_CompPageTimeValueLabel = nullptr;
lv_obj_t *ui_CompPageShotsStaticLabel = nullptr;
lv_obj_t *ui_CompPageShotsValueLabel = nullptr;
lv_obj_t *ui_CompPageStartButton = nullptr;
lv_obj_t *ui_CompPageStartButtonLabel = nullptr;
lv_obj_t *ui_CompPageResetButton = nullptr;
lv_obj_t *ui_CompPageResetButtonLabel = nullptr;

// Bubble Level UI Elements
static lv_obj_t *ui_BubbleLevelCanvas = nullptr;
static lv_obj_t *ui_RollAngleLabel = nullptr;
static lv_timer_t *ui_level_update_timer = nullptr;

// LVGL Timer for live data updates on this page
static lv_timer_t *competition_page_data_refresh_timer = nullptr;

// --- Colors for the Bubble Level ---
static lv_color_t color_page_bg_bubble;
static lv_color_t color_tube_bg_bubble;
static lv_color_t color_bubble_green;
// ...existing code for the rest of the file...
