#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Options_Page.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OPTIONS_PAGE_H
#define UI_OPTIONS_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Options_Page
extern void ui_Options_Page_screen_init(void);
extern void ui_Options_Page_screen_destroy(void);
extern lv_obj_t * ui_Options_Page;
extern lv_obj_t * ui_OptionsPageLabel;
extern void ui_event_Page_1(lv_event_t * e);
extern lv_obj_t * ui_Page_1;
extern lv_obj_t * ui_BubbleLevelBTN;
extern void ui_event_Page2(lv_event_t * e);
extern lv_obj_t * ui_Page2;
extern lv_obj_t * ui_HorizonBTN;
extern void ui_event_Page3(lv_event_t * e);
extern lv_obj_t * ui_Page3;
extern lv_obj_t * ui_ShotCounterBTN;
extern void ui_event_Page4(lv_event_t * e);
extern lv_obj_t * ui_Page4;
extern lv_obj_t * ui_StageTimerBTN1;
extern void ui_event_Page5(lv_event_t * e);
extern lv_obj_t * ui_Page5;
extern lv_obj_t * ui_CompetitionBTN1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Page1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

