#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Stage_Timer_Page.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STAGE_TIMER_PAGE_H
#define UI_STAGE_TIMER_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui_helpers.h" // Assuming this is where _ui_screen_change is, or it's in ui.h / lvgl.h
#include "ui_events.h"  // For event definitions if any are global

// SCREEN: ui_Stage_Timer_Page
extern void ui_Stage_Timer_Page_screen_init(void);
extern void ui_Stage_Timer_Page_screen_destroy(void);
extern lv_obj_t * ui_Stage_Timer_Page;

// Title Label
extern lv_obj_t * ui_StageTimerPageTitleLabel; // Corrected from ui_SrageTimerPageLabel

// Timer Value Display
extern lv_obj_t * ui_StageTimerDisplayValueLabel;

// Timer Control Buttons & Event Handlers
extern void ui_event_StageTimerAddButton(lv_event_t * e);
extern lv_obj_t * ui_StageTimerAddButton;
extern lv_obj_t * ui_StageTimerAddLabel;

extern void ui_event_StageTimerSubButton(lv_event_t * e);
extern lv_obj_t * ui_StageTimerSubButton;
extern lv_obj_t * ui_StageTimerSubLabel;

extern void ui_event_StageTimerResetButton(lv_event_t * e);
extern lv_obj_t * ui_StageTimerResetButton;
extern lv_obj_t * ui_StageTimerResetLabel;

extern void ui_event_StageTimerStartPauseButton(lv_event_t * e);
extern lv_obj_t * ui_StageTimerStartPauseButton;
extern lv_obj_t * ui_StageTimerStartPauseLabel;

// Existing Navigation Buttons (as per your original file)
extern void ui_event_Page4HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page4HomeBTN;
extern lv_obj_t * ui_Page4HomeBTN1;

extern void ui_event_Page4PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page4PrevBTN;
extern lv_obj_t * ui_Page4PrevBTN1;

extern void ui_event_Page4NextBTN(lv_event_t * e);
extern lv_obj_t * ui_Page4NextBTN;
extern lv_obj_t * ui_Page4NextBTN1;

/////////////////////////////////////////////////////////////////////////////////////////////
// ... (other extern declarations) ...

// --- Functions to access stage timer data and actions ---
extern int32_t ui_stage_timer_get_time_remaining_seconds(void);
extern uint32_t ui_stage_timer_get_current_set_time_seconds(void);
extern bool ui_stage_timer_is_timer_running(void);
extern void ui_stage_timer_start_timer_action(void); // Renamed to avoid conflict if you name event handlers similarly
extern void ui_stage_timer_pause_timer_action(void); // Renamed
extern void ui_stage_timer_reset_timer_to_set_time_action(void); // Renamed
//////////////////////////////////////////////////////////////////////////////////////////////

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif