#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Shot_Counter_Page.cpp"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"              // This should include lvgl.h and other necessary headers
#include "ui_modern_theme.h" // DEADEYE theme support
// ui.h should ensure ui_Shot_Counter_Page.h is included for DEFAULT_INITIAL_SHOT_COUNT

// --- Definitions for global UI object pointers for this screen ---
lv_obj_t *ui_Shot_Counter_Page = nullptr;
lv_obj_t *ui_Label6 = nullptr; // Title "Shot Counter"
lv_obj_t *ui_Page3HomeBTN = nullptr;
lv_obj_t *ui_Page3HomeBTN1 = nullptr; // Label for Home button
lv_obj_t *ui_Page3PrevBTN = nullptr;
lv_obj_t *ui_Page3PrevBTN1 = nullptr; // Label for Prev button
lv_obj_t *ui_Page3NextBTN = nullptr;
lv_obj_t *ui_Page3NextBTN1 = nullptr; // Label for Next button

// New UI Element Objects for Shot Counter
lv_obj_t *ui_ShotDisplayValueLabel = nullptr;
lv_obj_t *ui_ShotAddButton = nullptr;
lv_obj_t *ui_ShotAddLabel = nullptr;
lv_obj_t *ui_ShotSubtractButton = nullptr;
lv_obj_t *ui_ShotSubtractLabel = nullptr;
lv_obj_t *ui_ShotResetButton = nullptr;
lv_obj_t *ui_ShotResetButtonLabel = nullptr;

// --- Static variables for shot counting ---
static int current_set_shot_count;
static int shots_remaining_count;

// --- Forward declaration for the update helper ---
static void update_shot_display_label(void);

// --- Functions to access shot counter data and actions (for Competition Page) ---
int ui_shot_counter_get_shots_remaining(void)
{
    return shots_remaining_count;
}

int ui_shot_counter_get_current_set_shot_count(void)
{
    return current_set_shot_count;
}

// Resets remaining shots to whatever current_set_shot_count is.
void ui_shot_counter_reset_to_set_count(void)
{
    shots_remaining_count = current_set_shot_count;
    if (lv_scr_act() == ui_Shot_Counter_Page && ui_ShotDisplayValueLabel != nullptr)
    {
        update_shot_display_label();
    }
}

// --- Function to reset both counts to the defined default value ---
void ui_shot_counter_reset_all_to_default(void)
{ // No longer takes an argument
    // ...existing code for the rest of the file...
}
