#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\ui_Shot_Counter_Page.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SHOT_COUNTER_PAGE_H
#define UI_SHOT_COUNTER_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h" // Or "ui.h" if it includes lvgl.h

// Define your desired default initial shot count here
#define DEFAULT_INITIAL_SHOT_COUNT 5 

// SCREEN: ui_Shot_Counter_Page
extern void ui_Shot_Counter_Page_screen_init(void);
extern void ui_Shot_Counter_Page_screen_destroy(void);
extern lv_obj_t * ui_Shot_Counter_Page;
extern lv_obj_t * ui_Label6; // Title "Shot Counter"
extern void ui_event_Page3HomeBTN(lv_event_t * e);
extern lv_obj_t * ui_Page3HomeBTN;
extern lv_obj_t * ui_Page3HomeBTN1;
extern void ui_event_Page3PrevBTN(lv_event_t * e);
extern lv_obj_t * ui_Page3PrevBTN;
extern lv_obj_t * ui_Page3PrevBTN1;
extern void ui_event_Page3NextBTN(lv_event_t * e);
extern lv_obj_t * ui_Page3NextBTN;
extern lv_obj_t * ui_Page3NextBTN1;

// New UI Element Objects for Shot Counter
extern lv_obj_t * ui_ShotDisplayValueLabel;
extern void ui_event_ShotAddButton(lv_event_t * e);
extern lv_obj_t * ui_ShotAddButton;
extern lv_obj_t * ui_ShotAddLabel;
extern void ui_event_ShotSubtractButton(lv_event_t * e);
extern lv_obj_t * ui_ShotSubtractButton;
extern lv_obj_t * ui_ShotSubtractLabel;
extern void ui_event_ShotResetButton(lv_event_t * e);
extern lv_obj_t * ui_ShotResetButton;
extern lv_obj_t * ui_ShotResetButtonLabel;


// --- Functions to access shot counter data and actions ---
extern int ui_shot_counter_get_shots_remaining(void);
extern int ui_shot_counter_get_current_set_shot_count(void);
extern void ui_shot_counter_reset_to_set_count(void); // Resets remaining to current_set
extern void ui_shot_counter_decrement_shot(void);     // Decrements remaining shots
extern void ui_external_decrement_shot_count(void);   // For recoil when this page is active

// --- Function to reset both counts to the defined default value ---
extern void ui_shot_counter_reset_all_to_default(void); // Takes no arguments


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*UI_SHOT_COUNTER_PAGE_H*/
