#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\backup\\ui.c"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "ui_battery_indicator.h"
#include "ui_splash_screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    // Initialize modern theme system first
    ui_modern_theme_init();

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // Initialize settings before other screens
    ui_settings_load_defaults();

    // Initialize splash screen first
    ui_splash_screen_init();

    // Initialize both original and modern screens
    ui_Options_Page_screen_init();
    ui_modern_options_page_init();
    ui_Bubble_Level_Page_screen_init();
    ui_Artificial_Horizon_Page_screen_init();
    ui_Shot_Counter_Page_screen_init();
    ui_Stage_Timer_Page_screen_init();
    ui_Competition_Page_screen_init();
    ui_Settings_Page_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    // Load splash screen first
    lv_disp_load_scr(ui_SplashScreen);

    // Start splash screen animation
    ui_splash_start_animation();

    // Create the battery indicator on the top layer AFTER all screens are initialized
    ui_battery_indicator_create(lv_layer_top());
}

void ui_destroy(void)
{
    ui_Options_Page_screen_destroy();
    ui_modern_options_page_destroy();
    ui_Bubble_Level_Page_screen_destroy();
    ui_Artificial_Horizon_Page_screen_destroy();
    ui_Shot_Counter_Page_screen_destroy();
    ui_Stage_Timer_Page_screen_destroy();
    ui_Competition_Page_screen_destroy();
    ui_Settings_Page_screen_destroy();
}