#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\backup\\ui_Artificial_Horizon_Page.c"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"                           // Should include lvgl.h and all other ui_*.h files
#include "ui_modern_theme.h"              // DEADEYE theme support
#include "ui_artificial_horizon_widget.h" // Our custom widget header

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Artificial_Horizon_Page;
lv_obj_t *ui_ArtificialHorizonPageLabel;
lv_obj_t *ui_Page2HomeBTN;
lv_obj_t *ui_HomeBTN1;
lv_obj_t *ui_Page2PrevBTN;
lv_obj_t *ui_Page2PrevBTN1;
lv_obj_t *ui_Page2NextBTN2; // Assuming this is the button object
lv_obj_t *ui_Page2NextBTN;  // Assuming this is the label for the next button (as per your .h)
lv_obj_t *ui_Label5;        // A general label, perhaps a title or unused.

// CUSTOM VARIABLES for Artificial Horizon
lv_obj_t *uic_ArtificialHorizon;             // The container object for the AHRS, declared in .h
static ui_ahrs_widget_t ahrs_data;           // Static data structure for our AHRS widget
static lv_timer_t *ahrs_update_timer = NULL; // Timer for updating the AHRS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
// Event handler prototypes (these should be defined in ui_events.c or similar)
// extern void ui_event_Page2HomeBTN(lv_event_t * e);
// extern void ui_event_Page2PrevBTN(lv_event_t * e);
// extern void ui_event_Page2NextBTN2(lv_event_t * e); // Or whatever the correct event for next is

// Timer callback function to update the artificial horizon
static void update_artificial_horizon_widget_timer_cb(lv_timer_t *timer)
{
    // If you passed &ahrs_data as user_data to the timer:
    // ui_ahrs_widget_t* data = (ui_ahrs_widget_t*)timer->user_data;
    // update_artificial_horizon_widget(data);
    // Otherwise, if using the static global:
    update_artificial_horizon_widget(&ahrs_data);
}

///////////////////// SCREENS ////////////////////
void ui_Artificial_Horizon_Page_screen_init(void)
{
    ui_Artificial_Horizon_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Artificial_Horizon_Page, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // Apply DEADEYE theme
    ui_modern_theme_apply_page_background(ui_Artificial_Horizon_Page);

    // Main Page Label (e.g., "Artificial Horizon")
    ui_ArtificialHorizonPageLabel = lv_label_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_ArtificialHorizonPageLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ArtificialHorizonPageLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ArtificialHorizonPageLabel, 0);
    lv_obj_set_y(ui_ArtificialHorizonPageLabel, -125); // Adjust Y position as needed
    lv_obj_set_align(ui_ArtificialHorizonPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArtificialHorizonPageLabel, "DEADEYE HORIZON");
    ui_modern_theme_apply_title_style(ui_ArtificialHorizonPageLabel);

    // Container for the Artificial Horizon (uic_ArtificialHorizon)
    if (!uic_ArtificialHorizon)
    { // Check if it was created by SLS, if not, create it.
        uic_ArtificialHorizon = lv_obj_create(ui_Artificial_Horizon_Page);
    }

    // Set size and position for the AHRS container
    lv_obj_set_width(uic_ArtificialHorizon, 160);
    lv_obj_set_height(uic_ArtificialHorizon, 120);
    lv_obj_set_x(uic_ArtificialHorizon, 0);
    lv_obj_set_y(uic_ArtificialHorizon, -10); // Adjust Y to position below title, above buttons
    lv_obj_set_align(uic_ArtificialHorizon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(uic_ArtificialHorizon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // Style the container: make it transparent, no border, no padding, so canvas fills it.
    lv_obj_set_style_bg_opa(uic_ArtificialHorizon, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(uic_ArtificialHorizon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(uic_ArtificialHorizon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the artificial horizon widget inside the container
    create_artificial_horizon_widget(uic_ArtificialHorizon, &ahrs_data, 160, 120);

    // Create and start the timer for AHRS updates
    if (ahrs_update_timer)
    { // Delete old timer if it exists (e.g., if screen re-initialized)
        lv_timer_del(ahrs_update_timer);
        ahrs_update_timer = NULL;
    }
    ahrs_update_timer = lv_timer_create(update_artificial_horizon_widget_timer_cb, 250, NULL); // 50ms period, no user_data directly (uses static)
    // If you want to pass ahrs_data via user_data:
    // ahrs_update_timer = lv_timer_create(update_artificial_horizon_widget_timer_cb, 50, &ahrs_data);

    // Home Button (ui_Page2HomeBTN with label ui_HomeBTN1)
    ui_Page2HomeBTN = lv_btn_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_Page2HomeBTN, 50);  // Example size
    lv_obj_set_height(ui_Page2HomeBTN, 25); // Example size
    lv_obj_set_x(ui_Page2HomeBTN, -60);     // Example position
    lv_obj_set_y(ui_Page2HomeBTN, 125);     // Example position
    lv_obj_set_align(ui_Page2HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page2HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Page2HomeBTN, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    // Add event callback for Home button
    lv_obj_add_event_cb(ui_Page2HomeBTN, ui_event_Page2HomeBTN, LV_EVENT_ALL, NULL);

    ui_HomeBTN1 = lv_label_create(ui_Page2HomeBTN);
    lv_label_set_text(ui_HomeBTN1, "Home");
    lv_obj_set_align(ui_HomeBTN1, LV_ALIGN_CENTER);

    // Previous Button (ui_Page2PrevBTN with label ui_Page2PrevBTN1)
    ui_Page2PrevBTN = lv_btn_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_Page2PrevBTN, 50);
    lv_obj_set_height(ui_Page2PrevBTN, 25);
    lv_obj_set_x(ui_Page2PrevBTN, 0);
    lv_obj_set_y(ui_Page2PrevBTN, 125);
    lv_obj_set_align(ui_Page2PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page2PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page2PrevBTN, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_Page2PrevBTN, ui_event_Page2PrevBTN, LV_EVENT_ALL, NULL);

    ui_Page2PrevBTN1 = lv_label_create(ui_Page2PrevBTN);
    lv_label_set_text(ui_Page2PrevBTN1, "Prev");
    lv_obj_set_align(ui_Page2PrevBTN1, LV_ALIGN_CENTER);

    // Next Button (ui_Page2NextBTN2 with label ui_Page2NextBTN)
    // Note: Your .h has ui_Page2NextBTN2 as the button and ui_Page2NextBTN as the label.
    ui_Page2NextBTN2 = lv_btn_create(ui_Artificial_Horizon_Page);
    lv_obj_set_width(ui_Page2NextBTN2, 50);
    lv_obj_set_height(ui_Page2NextBTN2, 25);
    lv_obj_set_x(ui_Page2NextBTN2, 60);
    lv_obj_set_y(ui_Page2NextBTN2, 125);
    lv_obj_set_align(ui_Page2NextBTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page2NextBTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page2NextBTN2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_Page2NextBTN2, ui_event_Page2NextBTN2, LV_EVENT_ALL, NULL);

    ui_Page2NextBTN = lv_label_create(ui_Page2NextBTN2); // This is the label for the NEXT button
    lv_label_set_text(ui_Page2NextBTN, "Next");
    lv_obj_set_align(ui_Page2NextBTN, LV_ALIGN_CENTER);

    // If ui_Label5 is a different label, initialize it here based on SLS export
    // For example:
    // ui_Label5 = lv_label_create(ui_Artificial_Horizon_Page);
    // lv_label_set_text(ui_Label5, "Some other info");
    // lv_obj_align(ui_Label5, LV_ALIGN_BOTTOM_LEFT, 10, -10); // Example position
    // If ui_Label5 was intended as the main title, the ui_ArtificialHorizonPageLabel above handles that.
    // If ui_Label5 is not used, you can remove its declaration and usage.
    // For now, I'll assume ui_ArtificialHorizonPageLabel is the main title.
    // If ui_Label5 is meant to be the title, replace ui_ArtificialHorizonPageLabel with ui_Label5 above.
}

// This function should be called when the screen is being left or destroyed
// to clean up custom resources like timers and allocated buffers.
void ui_Artificial_Horizon_Page_screen_destroy(void)
{
    // Delete the timer
    if (ahrs_update_timer)
    {
        lv_timer_del(ahrs_update_timer);
        ahrs_update_timer = NULL;
    }

    // Destroy AHRS widget custom data (e.g., canvas buffer)
    // The canvas object itself and reticle lines will be deleted by LVGL
    // when their parent (uic_ArtificialHorizon or ui_Artificial_Horizon_Page) is deleted.
    destroy_artificial_horizon_widget(&ahrs_data);

    // LVGL will automatically delete all child objects of ui_Artificial_Horizon_Page
    // when ui_Artificial_Horizon_Page itself is deleted by the screen management system.
    // If ui_Artificial_Horizon_Page_screen_destroy is *only* for custom resources
    // before the main screen object is deleted, this is correct.
    // If this function is *also* responsible for deleting ui_Artificial_Horizon_Page,
    // then that lv_obj_del(ui_Artificial_Horizon_Page) call would happen after this.
    // Typically, screen changing logic in ui.c handles deleting the old screen object.
}
