#line 1 "C:\\Users\\chadgroves\\OneDrive - Simventions, Inc\\Desktop\\ShootingAssistant_V4\\backup\\ui_Shot_Counter_Page.c"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"              // This should include lvgl.h and other necessary headers
#include "ui_modern_theme.h" // DEADEYE theme support
// ui.h should ensure ui_Shot_Counter_Page.h is included for DEFAULT_INITIAL_SHOT_COUNT

// --- Definitions for global UI object pointers for this screen ---
lv_obj_t *ui_Shot_Counter_Page;
lv_obj_t *ui_Label6; // Title "Shot Counter"
lv_obj_t *ui_Page3HomeBTN;
lv_obj_t *ui_Page3HomeBTN1; // Label for Home button
lv_obj_t *ui_Page3PrevBTN;
lv_obj_t *ui_Page3PrevBTN1; // Label for Prev button
lv_obj_t *ui_Page3NextBTN;
lv_obj_t *ui_Page3NextBTN1; // Label for Next button

// New UI Element Objects for Shot Counter
lv_obj_t *ui_ShotDisplayValueLabel;
lv_obj_t *ui_ShotAddButton;
lv_obj_t *ui_ShotAddLabel;
lv_obj_t *ui_ShotSubtractButton;
lv_obj_t *ui_ShotSubtractLabel;
lv_obj_t *ui_ShotResetButton;
lv_obj_t *ui_ShotResetButtonLabel;

// --- Static variables for shot counting ---
// DEFAULT_INITIAL_SHOT_COUNT is now defined in ui_Shot_Counter_Page.h
static int current_set_shot_count;
static int shots_remaining_count;

// --- Forward declaration for the update helper ---
static void update_shot_display_label(void);

// --- Functions to access shot counter data and actions (for Competition Page) ---
int ui_shot_counter_get_shots_remaining(void)
{
    return shots_remaining_count;
}

int ui_shot_counter_get_current_set_shot_count(void)
{
    return current_set_shot_count;
}

// Resets remaining shots to whatever current_set_shot_count is.
void ui_shot_counter_reset_to_set_count(void)
{
    shots_remaining_count = current_set_shot_count;
    if (lv_scr_act() == ui_Shot_Counter_Page && ui_ShotDisplayValueLabel != NULL)
    {
        update_shot_display_label();
    }
}

// --- Function to reset both counts to the defined default value ---
void ui_shot_counter_reset_all_to_default(void)
{ // No longer takes an argument
    int default_count = ui_settings_get_default_shot_count();
    current_set_shot_count = default_count;
    shots_remaining_count = default_count;

    // If this page is active, update its label.
    if (lv_scr_act() == ui_Shot_Counter_Page && ui_ShotDisplayValueLabel != NULL)
    {
        update_shot_display_label();
    }
}

// --- Function to decrement shot count globally ---
void ui_shot_counter_decrement_shot(void)
{
    if (shots_remaining_count > 0)
    {
        shots_remaining_count--;
    }
}

// --- Event functions for existing navigation buttons ---
void ui_event_Page3HomeBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Options_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Options_Page_screen_init);
    }
}

void ui_event_Page3PrevBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Artificial_Horizon_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                          &ui_Artificial_Horizon_Page_screen_init);
    }
}

void ui_event_Page3NextBTN(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Stage_Timer_Page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Stage_Timer_Page_screen_init);
    }
}

// --- Event functions for new shot counter buttons (on this page) ---
void ui_event_ShotAddButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        if (current_set_shot_count < 99)
        {
            current_set_shot_count++;
        }
        shots_remaining_count = current_set_shot_count;
        update_shot_display_label();
    }
}

void ui_event_ShotSubtractButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        if (current_set_shot_count > 0)
        {
            current_set_shot_count--;
        }
        shots_remaining_count = current_set_shot_count;
        update_shot_display_label();
    }
}

// Reset button on *this* page (Shot_Counter_Page)
void ui_event_ShotResetButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        ui_shot_counter_reset_all_to_default(); // Calls the updated function
        update_shot_display_label();            // Ensure this page's label is updated
    }
}

// --- Helper function to update the shot count display label ---
static void update_shot_display_label(void)
{
    if (ui_ShotDisplayValueLabel)
    {
        char buf[8]; // Increased buffer size for safety
        int result = lv_snprintf(buf, sizeof(buf), "%d", shots_remaining_count);
        if (result >= 0 && result < sizeof(buf))
        {
            lv_label_set_text(ui_ShotDisplayValueLabel, buf);
        }
    }
}

// --- Public function for accelerometer integration (or other external decrement) ---
void ui_external_decrement_shot_count(void)
{
    if (lv_scr_act() == ui_Shot_Counter_Page)
    {
        if (shots_remaining_count > 0)
        {
            shots_remaining_count--;
            update_shot_display_label();
        }
    }
}

// --- Build functions ---
void ui_Shot_Counter_Page_screen_init(void)
{
    // Initialize shot counter values from settings
    current_set_shot_count = ui_settings_get_default_shot_count();
    shots_remaining_count = current_set_shot_count;

    ui_Shot_Counter_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Shot_Counter_Page, LV_OBJ_FLAG_SCROLLABLE);

    // Apply DEADEYE theme
    ui_modern_theme_apply_page_background(ui_Shot_Counter_Page);

    ui_Label6 = lv_label_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -125);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "DEADEYE SHOT COUNTER");
    ui_modern_theme_apply_title_style(ui_Label6);

    ui_ShotDisplayValueLabel = lv_label_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_ShotDisplayValueLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ShotDisplayValueLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ShotDisplayValueLabel, 0);
    lv_obj_set_y(ui_ShotDisplayValueLabel, -45);
    lv_obj_set_align(ui_ShotDisplayValueLabel, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_ShotDisplayValueLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_modern_theme_apply_primary_text_style(ui_ShotDisplayValueLabel);

    update_shot_display_label();

    ui_ShotSubtractButton = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_ShotSubtractButton, 50);
    lv_obj_set_height(ui_ShotSubtractButton, 30);
    lv_obj_align_to(ui_ShotSubtractButton, ui_ShotDisplayValueLabel, LV_ALIGN_OUT_LEFT_MID, -25, 130);
    lv_obj_add_flag(ui_ShotSubtractButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ShotSubtractButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_ShotSubtractButton);

    ui_ShotSubtractLabel = lv_label_create(ui_ShotSubtractButton);
    lv_obj_set_align(ui_ShotSubtractLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShotSubtractLabel, "-");

    ui_ShotAddButton = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_ShotAddButton, 50);
    lv_obj_set_height(ui_ShotAddButton, 30);
    lv_obj_align_to(ui_ShotAddButton, ui_ShotDisplayValueLabel, LV_ALIGN_OUT_RIGHT_MID, 25, 130);
    lv_obj_add_flag(ui_ShotAddButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ShotAddButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_ShotAddButton);
    lv_obj_clear_flag(ui_ShotAddButton, LV_OBJ_FLAG_SCROLLABLE);

    ui_ShotAddLabel = lv_label_create(ui_ShotAddButton);
    lv_obj_set_align(ui_ShotAddLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShotAddLabel, "+");

    ui_ShotResetButton = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_ShotResetButton, 50);
    lv_obj_set_height(ui_ShotResetButton, 30);
    lv_obj_set_x(ui_ShotResetButton, 0);
    lv_obj_set_y(ui_ShotResetButton, 85);
    lv_obj_set_align(ui_ShotResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShotResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ShotResetButton, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_ShotResetButton);

    ui_ShotResetButtonLabel = lv_label_create(ui_ShotResetButton);
    lv_obj_set_align(ui_ShotResetButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShotResetButtonLabel, "Reset");

    const lv_coord_t nav_btn_y_offset = 125;

    ui_Page3HomeBTN = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Page3HomeBTN, 50);
    lv_obj_set_height(ui_Page3HomeBTN, 25);
    lv_obj_set_x(ui_Page3HomeBTN, -60);
    lv_obj_set_y(ui_Page3HomeBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page3HomeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3HomeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page3HomeBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page3HomeBTN);

    ui_Page3HomeBTN1 = lv_label_create(ui_Page3HomeBTN);
    lv_obj_set_align(ui_Page3HomeBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page3HomeBTN1, "HOME");

    ui_Page3PrevBTN = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Page3PrevBTN, 50);
    lv_obj_set_height(ui_Page3PrevBTN, 25);
    lv_obj_set_x(ui_Page3PrevBTN, 0);
    lv_obj_set_y(ui_Page3PrevBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page3PrevBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3PrevBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page3PrevBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page3PrevBTN);

    ui_Page3PrevBTN1 = lv_label_create(ui_Page3PrevBTN);
    lv_obj_set_align(ui_Page3PrevBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page3PrevBTN1, "PREV");

    ui_Page3NextBTN = lv_btn_create(ui_Shot_Counter_Page);
    lv_obj_set_width(ui_Page3NextBTN, 50);
    lv_obj_set_height(ui_Page3NextBTN, 25);
    lv_obj_set_x(ui_Page3NextBTN, 60);
    lv_obj_set_y(ui_Page3NextBTN, nav_btn_y_offset);
    lv_obj_set_align(ui_Page3NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page3NextBTN, LV_OBJ_FLAG_SCROLLABLE);
    ui_modern_theme_apply_button_style(ui_Page3NextBTN);
    lv_obj_set_align(ui_Page3NextBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page3NextBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Page3NextBTN, LV_OBJ_FLAG_SCROLLABLE);

    ui_Page3NextBTN1 = lv_label_create(ui_Page3NextBTN);
    lv_obj_set_align(ui_Page3NextBTN1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page3NextBTN1, "Next");

    lv_obj_add_event_cb(ui_Page3HomeBTN, ui_event_Page3HomeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page3PrevBTN, ui_event_Page3PrevBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page3NextBTN, ui_event_Page3NextBTN, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_ShotAddButton, ui_event_ShotAddButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShotSubtractButton, ui_event_ShotSubtractButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShotResetButton, ui_event_ShotResetButton, LV_EVENT_ALL, NULL);

    update_shot_display_label();
}

void ui_Shot_Counter_Page_screen_destroy(void)
{
    if (ui_Shot_Counter_Page)
    {
        lv_obj_del(ui_Shot_Counter_Page);
    }

    ui_Shot_Counter_Page = NULL;
    ui_Label6 = NULL;
    ui_Page3HomeBTN = NULL;
    ui_Page3HomeBTN1 = NULL;
    ui_Page3PrevBTN = NULL;
    ui_Page3PrevBTN1 = NULL;
    ui_Page3NextBTN = NULL;
    ui_Page3NextBTN1 = NULL;

    ui_ShotDisplayValueLabel = NULL;
    ui_ShotAddButton = NULL;
    ui_ShotAddLabel = NULL;
    ui_ShotSubtractButton = NULL;
    ui_ShotSubtractLabel = NULL;
    ui_ShotResetButton = NULL;
    ui_ShotResetButtonLabel = NULL;
}
